### ISSUE TITLE
How to compile the project?

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [MotooriKashin/ef2#12]
Hi,

I have Visual Studio 2022 installed and followed your compilation instructions on the front page. However, I found that VSCode is not able to compile the project. I don't remember the exact error message, but it seems like some VSCode extension is required. So, I installed this one:

![image](https://user-images.githubusercontent.com/39968/220872431-7c9c9920-db4e-42cf-b6db-2464387f9460.png)

After that, when I press <kbd>F5</kbd>, I get this:

![image](https://user-images.githubusercontent.com/39968/220872606-7c6346b5-b547-434d-bf03-2f408f6aab75.png)

Have I missed anything?

**Comment by MotooriKashin** [comment]
oh. I am sorry.  This is my project when I first learned c++, so it is very rough in all aspects, especially when compiling with vscode. Now it seems incredible.  
Back to the question:
```
could not open ***resource.rc
```
It seems that the .rc file `src/resource.rc` is missing?
![image](https://user-images.githubusercontent.com/60416767/220890031-c8cff22d-2072-447a-9245-dcb86620b623.png)

In principle, it is impossible to lose files. So maybe it's a text encoding(GB2312) problem? In other words, this project cannot be compiled in a non-Chinese system? I think so. After all, for more general compatibility, I have always wanted to use utf-8 as the encoding. But I tried several times and failed. There may be solutions in VS, but it is difficult in VSCode or command line.  

You can try to remove the Chinese or garbled characters in the file(`src/resource.rc`). In addition, it is recommended to use `Ctrl+Shift+B` instead of `F5` for the compilation command.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks for pointing me in the right direction. I did some investigation and was able to successfully compile the project. Here's what I did:

As you suggested, I removed the jumbled characters in the resource file.
![image](https://user-images.githubusercontent.com/39968/221025477-69b1093a-c6d3-4917-a1ef-408703e8f4f0.png)

Then I modified tasks.json slightly.
![image](https://user-images.githubusercontent.com/39968/221025570-f46bbcbe-8547-4722-bdf7-5c087ac379fb.png)

Finally, I removed the Chinese characters in main.cpp.
![image](https://user-images.githubusercontent.com/39968/221025648-1b052cb9-75c3-4704-a96b-a449322571d9.png)

I'm not sure which step solved the problem, but I'm glad that I was able to compile the project. Thanks again for your help.

![image](https://user-images.githubusercontent.com/39968/221021982-0ea05ab7-a932-4c5e-af17-71601a958141.png)
